shortenerapp/urls.py
from django.urls import path
from . import views





urlpatterns = [
    path('form',views.form,name='form'),
    path('userList/',views.userList,name='userList'),
    path('addUsers/',views.addUsers,name='addUser'),
    path('signupTable/',views.addUsersFormSet,name='addUsers'),
    path('access/<slug>',views.erisimFormu,name='erisimFormu'),
    path('success',views.success,name='success'),
    path('htmx/create-user-form/',views.createUserForm,name='create-user-form'),
    path('',views.form,name='index'),
    path('<accessed_url>',views.shortenedRedirect),
    path('deleteUrl/<slug>',views.deleteUrl,name='deleteUrl'),
]

urlshortener/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import include, path






urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shortenerapp.urls')),
    path('accounts/', include('allauth.urls')),
]

shortenerapp/models.py
import json
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django_celery_beat.models import PeriodicTask, ClockedSchedule
from datetime import datetime, timedelta 
from django_enum_choices.fields import EnumChoiceField
from django.dispatch import receiver
from shortenerapp.enums import SendMailStatus
from django.db.models.signals import post_save

# Create your models here.


class Urls(models.Model):
    inUrl= models.URLField(blank=False,verbose_name="Kısaltmak istediğiniz URL'yi girin")
    outSlug= models.SlugField(null=False,blank=False,unique=True)
    timer = models.IntegerField(default=1,verbose_name="Kısa URL'niz kaç gün aktif olsun")
    expirationDate = models.DateTimeField(default=datetime.now(), blank=True)
    isActive = models.BooleanField(default = 1)
    dateStarted = models.DateTimeField(auto_now_add=True)
    isPublic = models.BooleanField(default= 1,verbose_name="URL'niz herkese açık olsun mu")
    ownerUser = models.ForeignKey(User, on_delete=models.CASCADE,related_name='owner',null=True)
    allowedUsers = models.ManyToManyField(User,related_name='allowed',)
    
    def __str__(self):
            return f"{self.outSlug}"
    
    def save(self,*args,**kwargs):
          self.expirationDate = self.expirationDate + timedelta(days=self.timer)
          super(Urls,self).save(*args,**kwargs)

class SendMail(models.Model):
      mail = models.EmailField(blank=False)
      mailtext = models.TextField(default="")
      sendingDate = models.DateTimeField(auto_now_add=True)
      done = models.BooleanField(default=False)
      status = EnumChoiceField(SendMailStatus, default=SendMailStatus.active)
      task = models.OneToOneField(
            PeriodicTask,
            on_delete=models.CASCADE,
            null=True,
            blank=True)
            
      def setup_task(self):
            pk = self.pk
            clocked, _ = ClockedSchedule.objects.get_or_create(
                  clocked_time = self.sendingDate)
            self.task = PeriodicTask.objects.create(
            name=self.mail + str(pk),
            task="sendNotification",
            clocked=clocked,
            kwargs = json.dumps({'pk':pk}),
            one_off=True,
            expires= self.sendingDate + timedelta(days=1),
            enabled = True,
            )
            self.save() 
      
      def delete(self, *args, **kwargs):
            if self.task is not None:
                  self.task.delete()
            return super(self.__class__, self).delete(*args, **kwargs)

@receiver(post_save, sender=SendMail)
def create_or_update_periodic_task(sender, instance, created, **kwargs):
    if created:
        instance.setup_task()
    else:
        if instance.task is not None:
            instance.task.enabled = instance.status == SendMailStatus.active
            instance.task.save()

shortenerapp/views.py
from datetime import timedelta
from random import randint
from django.forms import formset_factory
from django.utils import timezone
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required, user_passes_test
from shortenerapp.forms import MyResetPasswordForm, MySignupForm, URLGiris, kisiSecim
from .models import SendMail, Urls
from django.utils.crypto import get_random_string
from allauth.account.adapter import DefaultAccountAdapter
from allauth.account.models import EmailAddress
from django.conf import settings
from django.http import HttpRequest
from django.contrib.auth.models import User
# Create your views here.
def isAdmin(user):
    return user.is_superuser

def success(req,slug):
    slug = slug
    return render(req, 'success.html', {'slug':slug,'host':req.META['HTTP_HOST']}
                  )

def form(req):
    def generateSlug():
        slug= get_random_string(8)
        slug_is_wrong = True  
        while slug_is_wrong:
            slug_is_wrong = False
            other_objs_with_slug = Urls.objects.filter(outSlug=slug)
            if len(other_objs_with_slug) > 0:
                slug_is_wrong = True
            if slug_is_wrong:
                slug = get_random_string(8)
        return slug
    

    if req.method == "POST":
    
        slug = generateSlug()
        form = URLGiris(req.POST)
        if form.is_valid():
            url = Urls(inUrl = form.cleaned_data['inUrl'],outSlug = slug,timer = form.cleaned_data['timer'],isPublic = form.cleaned_data['isPublic'],ownerUser = req.user)
            url.save()
            mailDate = url.expirationDate + timedelta(days = -1, minutes = 1)   
            mailToSend = SendMail(mail = req.user.email, mailtext = "Url'inizin süresi 1 gün sonra dolacak.", sendingDate = mailDate)
            mailToSend.save()
            # mailToSend.setup_task()
            html = '/access/'+slug
            return redirect(html)   
    else:
        form = URLGiris()
        if req.user.is_authenticated:
            ownedUrls = Urls.objects.filter(ownerUser__id = req.user.pk)
            return render(req, 'index.html',
                {'form':form,'ownedUrls':ownedUrls,'host':req.META['HTTP_HOST']})
        return render(req, 'index.html',
                {'form':form})


def index(req):
    if req.user.is_authenticated():
        ownedUrls = Urls.objects.filter(ownerUser__id = req.user.pk)
        return render(req,'index.html',{'ownedUrls':ownedUrls})
    else:
        pass

def deleteUrl(req,slug):
    url = Urls.objects.get(outSlug=slug)
    url.delete()
    return redirect('#')

@login_required
def erisimFormu(req,slug):

    url = get_object_or_404(Urls,outSlug = slug)
    if url.isPublic == 1:
        return render(req,'success.html',{'slug':slug,'host':req.META['HTTP_HOST']})
    else:
        if req.method == "POST":
            form = kisiSecim(req.POST, instance= url)
            form.save()
            return render(req,'success.html',{'slug':slug,'host':req.META['HTTP_HOST']})
        else:
            form = kisiSecim(instance = url)
            return render(req, "access.html",{'form':form})


@user_passes_test(isAdmin)
def userList(req):
    users = User.objects.all()
    if req.method == "POST":
        form = MySignupForm(req.POST)
        if form.is_valid():

            accAda= DefaultAccountAdapter()
            
            user =accAda.new_user(req)

            username = form.cleaned_data["email"].split("@")[0]
            while True:
                if User.objects.filter(username = username).exists():
                    username = username + str(randint(0,1000))
                else:
                    break
            form.cleaned_data['username'] = username
            # accAda.populate_username(request,user) username'yi isim soyisimden alır. Biz epostadan alıyoruz
            accAda.save_user(req,user,form)
            try:
                mail =EmailAddress.objects.get(email= user.email)
                mail.verified = 1
                mail.primary = 1
                mail.save()
            except:
                emailVerifier = EmailAddress.objects.create(email = user.email, verified = 1, primary = 1, user_id = user.pk)
                emailVerifier.save()
            selected_groups = form.cleaned_data["groups"]
            print(selected_groups)
            for group in selected_groups:
                user.groups.add(group)
                
            send_password_reset(user)
            form = MySignupForm()
            return render(req,'userList.html',{'users':users,'form':form})
        else:

            return render(req,'userList.html',{'form':form, 'users':users})
    else:
        form = MySignupForm()
        return render(req,'userList.html',{'form':form, 'users':users})

@login_required
def shortenedRedirect(req,accessed_url):
    if Urls.objects.get(outSlug = accessed_url).isActive :
        if Urls.objects.get(outSlug = accessed_url).isPublic:
            if Urls.objects.get(outSlug = accessed_url).expirationDate < timezone.now():
                url = Urls.objects.get(outSlug = accessed_url).isActive = False
                url.save()
                return HttpResponseBadRequest()
            else:
                return HttpResponseRedirect(Urls.objects.get(outSlug = accessed_url).inUrl)
        else:
            if Urls.objects.get(outSlug = accessed_url).allowedUsers.contains(req.user):
                if Urls.objects.get(outSlug = accessed_url).expirationDate < timezone.now():
                    url = Urls.objects.get(outSlug = accessed_url).isActive = False
                    url.save()
                    return HttpResponseBadRequest()
                else:
                    return HttpResponseRedirect(Urls.objects.get(outSlug = accessed_url).inUrl)
            else:
                return HttpResponseBadRequest()
    else:
        return HttpResponseBadRequest()
    


def send_password_reset(user: settings.AUTH_USER_MODEL):
    request = HttpRequest()
    request.user = user
    request.META['HTTP_HOST'] = '127.0.0.1:8000'
    form = MyResetPasswordForm({"email": user.email})
    if form.is_valid():
        form.save(request)

@user_passes_test(isAdmin)
def addUsers(request):    
    if request.method == "POST":
        form = MySignupForm(request.POST)
        if form.is_valid():

            accAda= DefaultAccountAdapter()
            
            user =accAda.new_user(request)

            username = form.cleaned_data["email"].split("@")[0]
            while True:
                if User.objects.filter(username = username).exists():
                    username = username + str(randint(0,1000))
                else:
                    break
            form.cleaned_data['username'] = username
            # accAda.populate_username(request,user) username'yi isim soyisimden alır. Biz epostadan alıyoruz
            accAda.save_user(request,user,form)
            try:
                mail =EmailAddress.objects.get(email= user.email)
                mail.verified = 1
                mail.primary = 1
                mail.save()
            except:
                emailVerifier = EmailAddress.objects.create(email = user.email, verified = 1, primary = 1, user_id = user.pk)
                emailVerifier.save()
            selected_groups = form.cleaned_data["groups"]
            print(selected_groups)
            for group in selected_groups:
                user.groups.add(group)
                
            send_password_reset(user)
            return HttpResponse('Kayıt Başarılı')
        else:

            return render(request,'partials/_userForm.html',{'form':form})
    else:
        form = MySignupForm()

        return render(request,'addUsers.html',{'form':form})
        
def createUserForm(req):
    form = MySignupForm()
    return render(req,'partials/_userForm.html',{'form':form})


@user_passes_test(isAdmin)
def addUsersFormSet(request):    
    MySignupFormSet = formset_factory(form=MySignupForm,
    extra=1, can_delete=False, can_delete_extra=False
)
    if request.method == "POST":
        formset = MySignupFormSet(request.POST)
        if formset.is_valid():
            for form in formset:
                if form.is_valid():
                    if form.cleaned_data:
                        accAda= DefaultAccountAdapter()
                
                        user =accAda.new_user(request)
                        username = form.cleaned_data["email"].split("@")[0]
                        while True:
                            if User.objects.filter(username = username).exists():
                                username = username + str(randint(0,1000))
                            else:
                                break
                        form.cleaned_data['username'] = username
                        
                        # else:
                            
                        #     accAda.populate_username(request,user) #username'yi isim soyisimden alır. Biz epostadan alıyoruz
                        accAda.save_user(request,user,form)
                        try:
                            mail =EmailAddress.objects.get(email= user.email)
                            mail.verified = 1
                            mail.primary = 1
                            mail.save()
                        except:
                            emailVerifier = EmailAddress.objects.create(email = user.email, verified = 1, primary = 1, user_id = user.pk)
                            emailVerifier.save()
                        selected_groups = form.cleaned_data["groups"]                    
                        for group in selected_groups:
                            user.groups.add(group)    
                        send_password_reset(user)
            formset = MySignupFormSet()

shortenerapp/templates/partials/_form.html
<form action="{% url 'form' %}" method='POST'>
    {% csrf_token %}
    <div class="row"> 
        <div class="col-12">
            <div class="row">
                <div class="col-6">
                    <label for="">Kısaltmak istediğiniz URL'yi girin</label>
                    {{form.inUrl}}
                </div>
                <div class="col-4">
                    <label for="">
                        Kısaltılmış URL'niz kaç günlük olsun
                    </label>
                    {{form.timer}}
                </div>
                <div class="col-2">
                    <label for="id_isPublic">
                        Bu URL Herkese açık yapılsın mı? Cevabınız
                    </label>
                    {{form.isPublic}}
                </div>
            </div>
            <button class="btn btn-dark waves-effect waves-light" type="submit">Kısalt</button>
        </div>
    </div>
</form>

shortenerapp/templates/partials/_nav.html
{% comment %} <nav class="navbar navbar-expand-lg bg-primary navbar-dark">
    <div class="container">
        <a href="/" class="navbar-brand">URL Shortener</a>
    </div>
</nav> {% endcomment %}
{% load static %}
<div class="navbar-custom">
    <div class="container-fluid">
        
        <ul class="list-unstyled topnav-menu float-right mb-0">
            <li class="dropdown notification-list">
                <!-- Mobile menu toggle-->
                <a class="navbar-toggle nav-link">
                    <div class="lines">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </a>
                <!-- End mobile menu toggle-->
            </li>

            <li class="d-none d-sm-block">
                <form class="app-search">
                    <div class="app-search-box">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search...">
                            <div class="input-group-append">
                                <button class="btn" type="submit">
                                    <i class="fe-search"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </li>
            {% if user.is_authenticated %}
                {% if user.is_superuser %}
                    <li class="notification-list">
                        <a class="nav-link nav-user mr-0 waves-effect waves-light" href="/userList/">
                            <span class="pro-user-name ml-1">
                                Kullanıcı Listesi 
                            </span>
                        </a>
                    </li>
                {% endif %}
                <li class="dropdown notification-list">
                    <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect waves-light" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                        <span class="pro-user-name ml-1">
                            {{user.first_name}} {{user.last_name}}<i class="mdi mdi-chevron-down"></i> 
                        </span>
                    </a>
                    
                    <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                        <!-- item-->
                        <div class="dropdown-header noti-title">
                            <h6 class="text-overflow m-0">Hoşgeldiniz {{user.username}}</h6>
                        </div>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <i class="mdi mdi-account-circle"></i>
                            <span>Hesabım</span>
                        </a>
                        
                        <div class="dropdown-divider"></div>

                        <!-- item-->
                        <a href="accounts/logout" class="dropdown-item notify-item">
                            <i class="mdi mdi-logout"></i>
                            <span>Çıkış Yap</span>
                        </a>

                    </div>
                </li>
            {% else %}
            <li class="notification-list">
                <a class="nav-link nav-user mr-0 waves-effect waves-light" href="/accounts/login/">
                    <span class="pro-user-name ml-1">
                        Giriş Yap 
                    </span>
                </a>
            </li>
            <li class="notification-list">
                <a class="nav-link nav-user mr-0 waves-effect waves-light" href="/accounts/signup/">
                    <span class="pro-user-name ml-1">
                        Kaydol 
                    </span>
                </a>
            </li>
            {% endif %}
            
        </ul>

        <!-- LOGO -->
        <div class="logo-box">
            <a href="/" class="logo text-center">
                <span class="logo-lg">
                    <img src="{% static 'assets/images/logo-light.png' %}" alt="" height="20">
                    <!-- <span class="logo-lg-text-light">Xeria</span> -->
                </span>
                <span class="logo-sm">
                    <!-- <span class="logo-sm-text-dark">X</span> -->
                    <img src="{% static 'assets/images/logo-sm.png' %}" alt="" height="24">
                </span>
            </a>
        </div>

        
        <div class="clearfix"></div>
    </div>
</div>

shortenerapp/templates/partials/_userForm.html
{% load crispy_forms_tags %}

<div hx-target="this" hx-swap="outerHTML" class="mt-3 py-3 px-3 bg-white shadow border border-gray-100">
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-error">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-error">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
        <button type="submit" hx-post="."
        class="inline-flex items-center px-3 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-black bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Kaydet
        </button>
    </form>
</div>   